name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: 
      - gerador pacotes nuget
      - gerador imagens docker
    branches: [ master ]
    types:
      - requested
  
env:
  CAMINHO_PROJETO: ./Library/Library.csproj
  CAMINHO_PROJETO_TESTES: ./Library.Tests/Library.Tests.csproj

jobs:
  build_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: EasyDesk/action-dotnet-test@v1
        with:
          build-configuration: Release
          skip-build: false

#     - uses: actions/checkout@v2
    
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 5.0.x
        
#     - name: Build
#       run: dotnet build ${{ env.CAMINHO_PROJETO }}
    
#     - name: Test
#       run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity normal
