name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  CAMINHO_PROJETO: ./Library/Library.csproj
  CAMINHO_PROJETO_TESTES: ./Library.Tests/Library.Tests.csproj

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Build
      run: dotnet build ${{ env.CAMINHO_PROJETO }}
      
    - uses: actions/upload-artifact@main
      with:
        name: build artifacts
        path: public/
        
  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: build artifacts
        path: public
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Test
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity normal
