name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  CAMINHO_PROJETO: ./Library/Library.csproj
  CAMINHO_PROJETO_TESTES: ./Library.Tests/Library.Tests.csproj

jobs:
  build_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Build
      run: dotnet build ${{ env.CAMINHO_PROJETO }}
    
    - name: Test
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity normal
    
    - name: Publish
      run: dotnet publish ${{ env.CAMINHO_PROJETO }}
