name: Gerador imagem Docker

on:
  workflow_dispatch:
    inputs:
      versao:
        description: 'Versão'
        required: true
      
jobs:
  testar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Rodar testes
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: build_test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-conclusions: success

  gerar_imagem:
    needs: [testar]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -t ${{ github.repository }} .

      - name: Tag Docker image
        run: docker tag ${{ github.repository }} ${{ secrets.REPOSITORIO_DOCKER }}:${{ github.event.inputs.versao }}

      - name: Push Docker image
        run: docker push ${{ secrets.REPOSITORIO_DOCKER }}:${{ github.event.inputs.versao }}

      - name: Gerar tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.versao }}
          tag_prefix: 'd'
