name: .NET 5 + NuGet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pack_push:
    env:
      AMBIENTE_DESTINO: Release
      CAMINHO_PROJETO: ./Library/Library.csproj
      CAMINHO_PROJETO_TESTES: ./Library.Tests/Library.Tests.csproj
      DIRETORIO_DESTINO_PACOTE: ${{ github.workspace }}/out

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.5.0'

      - name: Determinar versão
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Executar testes automatizados
        run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal

      - name: Geração do pacote
        run: dotnet pack ${{ env.CAMINHO_PROJETO }} -c ${{ env.AMBIENTE_DESTINO }} -o ${{ env.DIRETORIO_DESTINO_PACOTE }} -p:PackageVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}

      - name: Push no NuGet
        run: dotnet nuget push ${{ env.DIRETORIO_DESTINO_PACOTE }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ secrets.NUGET_SERVER }}
