name: Buildar e testar aplicação

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master]

jobs:
  buildTest:
    runs-on: ubuntu-latest
    env:
      CAMINHO_PROJETO: ./Library/Library.csproj
      CAMINHO_PROJETO_TESTES: ./Library.Tests/Library.Tests.csproj
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Buildar aplicação
        run: dotnet build ${{ env.CAMINHO_PROJETO }}
        
      - name: Executar testes automatizados
        run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --no-restore --verbosity minimal
        
