name: Gerador pacotes NuGet

on:
  workflow_dispatch:
    inputs:
      versao:
        description: 'Versão'
        required: true

jobs:
  testar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Rodar testes
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: buildar_testar
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-conclusions: success

  gerar_pacote:
    needs: [testar]
    runs-on: ubuntu-latest
    env:
      AMBIENTE_DESTINO: Release
      CAMINHO_PROJETO: ./Library/Library.csproj
      DIRETORIO_DESTINO_PACOTE: ${{ github.workspace }}/out

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Geração do pacote
        run: >
          dotnet pack ${{ env.CAMINHO_PROJETO }} 
                   -c ${{ env.AMBIENTE_DESTINO }} 
                   -o ${{ env.DIRETORIO_DESTINO_PACOTE }} 
                   -p:PackageVersion=${{ github.event.inputs.versao }}
        
      - name: Push no NuGet
        run: >
          dotnet nuget push ${{ env.DIRETORIO_DESTINO_PACOTE }}/*.nupkg 
                         -k ${{ secrets.NUGET_API_KEY }} 
                         -s ${{ secrets.NUGET_SERVER }}

      - name: Gerar tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ format('n{0}', github.event.inputs.versao) }}
          tag_prefix: ''
