name: Testes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#   workflow_run:
#     workflows: 
#       - gerador pacotes nuget
#       - gerador imagens docker
#     branches: [ master ]
#     types:
#       - requested
  
jobs:
  testar:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: EasyDesk/action-dotnet-test@v1
        with:
          build-configuration: Release
          skip-build: false
