name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CAMINHO_PROJETO: ./Library/Library.csproj
      CAMINHO_PROJETO_TESTES: ./Library.Tests/Library.Tests.csproj
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/download-artifact@main
      with:
        name: build artifacts
        path: public
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Test
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity normal
