name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CAMINHO_PROJETO: ./Library/Library.csproj
      CAMINHO_PROJETO_TESTES: ./Library.Tests/Library.Tests.csproj
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Build
      run: dotnet build ${{ env.CAMINHO_PROJETO }}
    
    - name: Test
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --no-build --verbosity normal
