name: Testes

on:
  push:
    branches: [ master ]
    paths-ignore: ['**.md']
  pull_request:
    branches: [ master ]
    paths-ignore: ['**.md']
  workflow_run:
    workflows: 
      - Gerador imagem Docker
      - Gerador pacotes NuGet
    branches: [ master ]
    types:
      - requested
  
jobs:
  buildar_testar:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: EasyDesk/action-dotnet-test@v1
        with:
          build-configuration: Release
          skip-build: false
