name: gerar tag
on:
  workflow_run:
    workflows: 
      - Gerador imagem Docker
      - Gerador pacotes NuGet
    types:
      - completed
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - run: echo ${{ toJson(github.event.client_payload) }}
