name: Gerar tag
on:
  workflow_run:
    workflows: 
      - gerador imagens docker
      - gerador pacotes nuget
    types:
      - completed
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - run: echo ${{ parseJSON(github.event.workflow_run) }}
