name: Bump version
on:
  push:
    tags:
      - '*.*.*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Bump version and push tag
        id: bla
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: true
      
      - run: |
          echo ${{ steps.bla.outputs.new_tag }}
          echo ${{ steps.bla.outputs.new_version }}
          echo ${{ steps.bla.outputs.previous_tag }}
          echo ${{ steps.bla.outputs.changelog }}
