name: Bump version
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Bump version and push tag
        id: bla
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - run: |
          echo ${{ steps.bla.new_tag }}
          echo ${{ steps.bla.new_version }}
          echo ${{ steps.bla.previous_tag }}
          echo ${{ steps.bla.changelog }}
